#端口号
server:  port: 8001
 
#服务名称
spring:  application:    name: gez-eureka
 
#-------------------------------------------------EUREKA----------------------------------------------------------
#服务注册与发现(配置集群时指向除了本身之外的Eureka服务端注册地址)
eureka:
  client:    serviceUrl:
       defaultZone: http://localhost:8001/eureka
            #当不配置集群的时候打开下面的配置
            #不将自己注册到eureka
    register-with-eureka: false #表示是否注册自身到eureka服务器， 做集群是设置成true 生产配置为true
    fetch-registry: false #表示是否从eureka server服务器获得注册信息，生产配置为true  #因为该服务没有注册到其他注册中心，所以关闭从注册中心拉取服务列表。
    registry-fetch-interval-seconds: 5 #默认为30s 生产使用缺省时间，测试环境修改小点
    lease-renewal-interval-in-seconds: 5 #心跳时间，生产使用缺省时间，即服务续约间隔时间（缺省为30秒，生产使用缺省时间，测试环境修改小点）
    lease-expiration-duration-in-seconds: 10 #发呆时间，即服务续约到期时间（缺省为90秒，生产使用缺省时间，测试环境修改小点）
  server:
    renewalpercent-threshold: 0.49  #设置心跳正常的阀值，默认为1，测试时可以调低
    enableSelfPreservation: true #关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 5000 #续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms），测试环境修改小点
      #通过ip注册
  instance:
  # hostname: 34.........120 #本机ip地址，可不配
    prefer-ip-address: true    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#  environment: local #如果使用config 统一配置 environment也不需要
  
